/**
 * Same-process localhost fetch: verifies remote CSV fetch + dry-run without
 * blocking the HTTP server (parent event loop must process accepts).
 *
 * Run:
 *   pnpm exec ts-node --project tsconfig.scripts.json scripts/nfbc-remote-preview-selftest.ts
 *
 * Writes: tmp/nfbc-remote-preview.json (not committed).
 */
import { mkdirSync, readFileSync, writeFileSync } from "fs";
import http from "http";
import path from "path";
import type { AddressInfo } from "net";
import {
  createNfbcRemoteCsvAdapter,
  dryRunMatchMarketAdp,
  redactMarketAdpSourceUrl,
} from "../src/lib/marketAdp";
import { normalizeCatalogPlayers } from "../src/lib/playerCatalog";

const ROOT = path.resolve(__dirname, "..");

async function main(): Promise<void> {
  const csvPath = path.join(ROOT, "test-fixtures/market-adp/nfbc-like-adp.csv");
  const catalogPath = path.join(ROOT, "test-fixtures/market-adp/catalog-nfbc-match.json");
  const csv = readFileSync(csvPath, "utf8");

  const server = http.createServer((_req, res) => {
    res.setHeader("Content-Type", "text/csv");
    res.end(csv);
  });

  await new Promise<void>((resolve, reject) => {
    server.listen(0, "127.0.0.1", () => resolve());
    server.on("error", reject);
  });

  const port = (server.address() as AddressInfo).port;
  const url = `http://127.0.0.1:${port}/nfbc-like-adp.csv?token=secret-value-not-in-output`;

  const adapter = createNfbcRemoteCsvAdapter(url, { timeoutMs: 10_000 });
  const fetchedAt = new Date().toISOString();
  const vendorRows = await adapter.fetchRows({
    sourceName: adapter.displayName,
    fetchedAt,
  });

  const raw = JSON.parse(readFileSync(catalogPath, "utf8")) as unknown[];
  const catalog = normalizeCatalogPlayers(raw, () => undefined);
  const { matches, proposed_updates } = dryRunMatchMarketAdp(
    catalog,
    vendorRows,
    adapter.displayName,
    fetchedAt
  );

  let matched = 0;
  let ambiguous = 0;
  let unmatched_vendor = 0;
  for (const m of matches) {
    if (m.kind === "matched") matched++;
    else if (m.kind === "ambiguous") ambiguous++;
    else if (m.kind === "unmatched_vendor") unmatched_vendor++;
  }

  const stats = {
    source_cli: "nfbc",
    adapter_env: adapter.id,
    vendor_rows: vendorRows.length,
    catalog_players: catalog.length,
    matched,
    ambiguous,
    unmatched_vendor,
    proposed_update_count: proposed_updates.length,
  };

  const outPath = path.join(ROOT, "tmp/nfbc-remote-preview.json");
  mkdirSync(path.dirname(outPath), { recursive: true });
  const payload = {
    adapter_id: adapter.id,
    adapter_display_name: adapter.displayName,
    csv_path: null,
    remote_csv_url_redacted: redactMarketAdpSourceUrl(url),
    catalog_source: "catalog_json",
    fetched_at: fetchedAt,
    stats,
    matches,
    proposed_updates,
    notes: [
      "Dry-run only: no Mongo writes.",
      "Generated by scripts/nfbc-remote-preview-selftest.ts (same-process localhost; query redacted in remote_csv_url_redacted).",
    ],
  };
  writeFileSync(outPath, `${JSON.stringify(payload, null, 2)}\n`, "utf8");
  server.close();

  console.log(`Wrote ${outPath}`);
  console.log(JSON.stringify(stats, null, 2));
  if (String(payload.remote_csv_url_redacted).includes("token=")) {
    throw new Error("remote_csv_url_redacted must not include query string");
  }
  if (adapter.id !== "nfbc_remote_csv") throw new Error("expected nfbc_remote_csv");
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
